import json, re, warnings
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import pandas as pd
import numpy as np
from datetime import datetime
from typing import List, Dict, Any
warnings.filterwarnings('ignore')
np.random.seed(42)
import ollama
import subprocess, time
import requests 
import os, json, textwrap, warnings
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import Markdown, display
warnings.filterwarnings('ignore')

subprocess.Popen(["ollama","serve"], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
time.sleep(5)
try:
    r = requests.get("http://localhost:11434")
    print("✅ Ollama server active:", r.text)
except:
    print("❌ Server not responding — try increasing the sleep time")


#CONFIGURATION
LLM_PROVIDER = "ollama"
# ── Ollama (local — no key needed) ───────────────────────────────────────
OLLAMA_BASE_URL = "http://localhost:11434"
OLLAMA_MODEL = "llama3.2:3b"
print(f'🔌 LLM Provider: {LLM_PROVIDER}')
generated_rules = "# stub: LLM not configured\ndef check_validity(df): return df"
# Placeholder string representing generated validation rules (returns input unchanged)
generated_report = "# stub: LLM not configured"
# Placeholder for a natural language report generated by the LLM
stakeholder_summary = "# stub: LLM not configured"
comparative_analysis= "# stub: LLM not configured"
print('✅ LLM stubs defined')

def call_llm(prompt: str, system: str=None, max_tokens: int=1500) ->str:
    provider = LLM_PROVIDER.lower()
    try:
        if provider == 'ollama':
            import requests
            messages = []
            if system:
                messages.append({"role": "system", "content": system})
            messages.append({"role":"user", "content": prompt})
            payload = {
                "model": OLLAMA_MODEL,
                "messages": messages,
                "stream": False
            }
            r = requests.post(f'{OLLAMA_BASE_URL}/api/chat', json=payload, timeout=500)
            r.raise_for_status()
            return r.json()['message']['content']
        
        else:
            raise ValueError(
                f'Unknown provider:{provider}. Choose: ollama'
            )
    except Exception as e:
        return f"[LLM Error —{provider}]{type(e).__name__}: {e}"


path = r'C:\Users\acer\Desktop\Magistrale 1-02-2026\I anno\Data Ware House\Olist\csv'

order_item_df = pd.read_csv(os.path.join(path, "olist_order_items_dataset.csv"))
order_df = pd.read_csv(os.path.join(path, "olist_orders_dataset.csv"))
order_df = order_df.drop(columns=['order_status'])
product_df = pd.read_csv(os.path.join(path, "olist_products_dataset.csv"))
print("Colonne disponibili in Product:", product_df.columns.tolist())
product_df = product_df.drop(columns=['product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g',
'product_length_cm', 'product_height_cm', 'product_width_cm'])
customer_df = pd.read_csv(os.path.join(path, "olist_customers_dataset.csv"))
customer_df = customer_df.drop(columns=['customer_unique_id'])
seller_df = pd.read_csv(os.path.join(path, "olist_sellers_dataset.csv")) 
category_df = pd.read_csv(os.path.join(path, "product_category_name_translation.csv"))
category_df = category_df.drop(columns=['product_category_name_english'])
order_item_enriched_df = order_item_df.merge(
    order_df[['order_id', 'order_delivered_carrier_date']], 
    on='order_id', 
    how='left'
)

print(order_df.shape)
print(order_item_df.shape)
print(product_df.shape)
print(customer_df.shape)
print(seller_df.shape)
print(category_df.shape)

BASE_PATH = r'C:\Users\acer\Desktop\Magistrale 1-02-2026\I anno\Data Ware House\Olist\InitialDQ\\'
dq_order_df = pd.read_csv(BASE_PATH + 'dq_scorecard_order.csv')
dq_order_item_df = pd.read_csv(BASE_PATH + 'dq_scorecard_order_item.csv')
dq_product_df = pd.read_csv(BASE_PATH + 'dq_scorecard_product.csv')
dq_customer_df = pd.read_csv(BASE_PATH + 'dq_scorecard_customer.csv')
dq_seller_df = pd.read_csv(BASE_PATH + 'dq_scorecard_seller.csv')
dq_category_df = pd.read_csv(BASE_PATH + 'dq_scorecard_category.csv')
print('✅ Dataset and scorecard loaded successfully')

# ── Rebuild a simplified scorecard dictionary for LLM analysis

def create_scorecard(table_name: str, df: pd.DataFrame, dq_df: pd.DataFrame) -> dict:
    scorecard = {
        'table': table_name,
        'rows': len(df),
        'columns': list(df.columns),
        'overall_score': round(dq_df['Score'].mean(), 4),
        'dimensions': {
            row['Dimension']: {
                'score': row['Score'],
                'issues': int(row['Issues']),
                'details': row['Details']
            }
            for _, row in dq_df.iterrows()
        }
    }

    print(json.dumps(scorecard, indent=2))
    print(f"\n📦 Table: {scorecard['table']}")
    print(f"Overall Score: {scorecard['overall_score']:.2%}\n")
    print(f'✅ {table_name} dataset and simplified scorecard ready for LLM analysis')

    return scorecard

order_scorecard = create_scorecard('Order', order_df, dq_order_df)
order_item_scorecard = create_scorecard('OrderItem', order_item_df, dq_order_item_df)
product_scorecard = create_scorecard('Product', product_df, dq_product_df)
customer_scorecard = create_scorecard('Customer', customer_df, dq_customer_df)
seller_scorecard = create_scorecard('Seller', seller_df, dq_seller_df)
category_scorecard = create_scorecard('ProductCategoryName', category_df, dq_category_df)

#Natural Language DQ Audit Report

def generate_and_save_audit(scorecard: dict, output_dir: str):
    #Prende una scorecard già esistente, invoca l'LLM per l'audit e salva il report risultante in un file Markdown.
    table_name = scorecard['table']
    SYSTEM_AUDIT = """As an expert Data Quality Analyst with a focus on Data Warehousing, you will analyze a
    structured DQ scorecard to generate clear and strategic audit reports for business stakeholders. 
    Your focus should be on identifying the issues and providing actionable recommendations based on their 
    potential business impact."""
    scorecard_json = json.dumps(scorecard, indent=2)
    PROMPT_AUDIT =f"""Below is the Data Quality Assessment scorecard for the table in a retail Data Warehouse.
                      Analyze it and produce a structured audit report with:
                      1. Executive Summary (2–3 sentences)
                      2. Issues
                      3. Recommended Cleaning Tasks (ordered list)
                      SCORECARD:
                      {scorecard_json}
                    """
    
    print(f'🤖 Calling LLM for DQ Audit Report: {table_name}...\n')
    audit_report = call_llm(PROMPT_AUDIT, system=SYSTEM_AUDIT, max_tokens=1000)
    print('═'*70)
    print(f' LLM DATA QUALITY AUDIT REPORT — {table_name}')
    print('═'*70)
    print(audit_report)
    print('═'*70)
    file_friendly_name = table_name.lower().replace(" ", "_")
    audit_output_path = os.path.join(output_dir, f'dq_audit_{file_friendly_name}.md')
    os.makedirs(output_dir, exist_ok=True)
    with open(audit_output_path, 'w', encoding='utf-8') as f:
        f.write(f'# 📊 LLM Data Quality Audit Report — {table_name}\n\n')
        f.write(f'## Generated by LLM ({LLM_PROVIDER.capitalize()})\n\n')
        f.write(audit_report)
        print(f'✅ Audit report saved → {audit_output_path}')
    with open(audit_output_path, 'r', encoding='utf-8') as f:
        content = f.read()
    display(Markdown(content))


output_folder_audit_report = r'C:\Users\acer\Desktop\Magistrale 1-02-2026\I anno\Data Ware House\Olist\LLMResults\AuditReport\\'
generate_and_save_audit(order_scorecard, output_folder_audit_report)
generate_and_save_audit(order_item_scorecard, output_folder_audit_report)
generate_and_save_audit(product_scorecard, output_folder_audit_report)
generate_and_save_audit(customer_scorecard, output_folder_audit_report)
generate_and_save_audit(seller_scorecard, output_folder_audit_report)
generate_and_save_audit(category_scorecard, output_folder_audit_report)


